// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace csharp_boolflix.Migrations
{
    [DbContext(typeof(NetflixContext))]
    [Migration("20221012122100_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Actor", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int>("MediaLinkId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MediaLinkId");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Characteristic", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int>("MediaLinkId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MediaLinkId");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("Episode", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TVSerieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TVSerieId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Genre", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int>("MediaLinkId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MediaLinkId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MediaLink", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<bool?>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MediaLinks");
                });

            modelBuilder.Entity("Movie", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("MediaLinkId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MediaLinkId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("TVSerie", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MediaLinkId")
                        .HasColumnType("int");

                    b.Property<int?>("Seasons")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MediaLinkId");

                    b.ToTable("TvSeries");
                });

            modelBuilder.Entity("Actor", b =>
                {
                    b.HasOne("MediaLink", "MediaLink")
                        .WithMany("Actors")
                        .HasForeignKey("MediaLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaLink");
                });

            modelBuilder.Entity("Characteristic", b =>
                {
                    b.HasOne("MediaLink", "MediaLink")
                        .WithMany("Characteristics")
                        .HasForeignKey("MediaLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaLink");
                });

            modelBuilder.Entity("Episode", b =>
                {
                    b.HasOne("TVSerie", "TVSerie")
                        .WithMany("Episodes")
                        .HasForeignKey("TVSerieId");

                    b.Navigation("TVSerie");
                });

            modelBuilder.Entity("Genre", b =>
                {
                    b.HasOne("MediaLink", "MediaLink")
                        .WithMany("Genres")
                        .HasForeignKey("MediaLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaLink");
                });

            modelBuilder.Entity("Movie", b =>
                {
                    b.HasOne("MediaLink", "MediaLink")
                        .WithMany("Movies")
                        .HasForeignKey("MediaLinkId");

                    b.Navigation("MediaLink");
                });

            modelBuilder.Entity("TVSerie", b =>
                {
                    b.HasOne("MediaLink", "MediaLink")
                        .WithMany("TVSeries")
                        .HasForeignKey("MediaLinkId");

                    b.Navigation("MediaLink");
                });

            modelBuilder.Entity("MediaLink", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Characteristics");

                    b.Navigation("Genres");

                    b.Navigation("Movies");

                    b.Navigation("TVSeries");
                });

            modelBuilder.Entity("TVSerie", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
